services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: notes_db
      POSTGRES_USER: notes_user
      POSTGRES_PASSWORD: notes_password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U notes_user -d notes_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      NODE_ENV: development
      PORT: 4000
      DATABASE_URL: postgresql://notes_user:notes_password@db:5432/notes_db
      CORS_ORIGIN: http://localhost:8080
      LOG_LEVEL: info
    depends_on:
      db:
        condition: service_healthy
  
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
      args:
        API_URL: /api
    restart: unless-stopped
    ports:
      - "8080:80"
    depends_on:
      - api

  dozzle:
    image: amir20/dozzle:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - "8081:8080"
    environment:
      DOZZLE_ENABLE_ACTIONS: false
      DOZZLE_NO_ANALYTICS: true

volumes:
  postgres_data:
    driver: local
